Repository nextcloud/workflow_script, pull requests merged in 2023-07, with the labels that each got.

#184 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#183 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#187 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#188 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#190 Update OCP and other dependencies
  composer.json
  composer.lock
  lib/BackgroundJobs/Launcher.php
Labels: 3. to review, backport-request

#189 Add Dependabot configuration
  .github/dependabot.yml
Labels: 3. to review

#192 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
