Repository nextcloud/workflow_script, pull requests merged in 2023-03, with the labels that each got.

#147 vendor is now necessary to ship
  .nextcloudignore
  appinfo/info.xml
Labels: 3. to review, bug

#149 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#148 chore: Add Nextcloud 27 support on master
  appinfo/info.xml
Labels: 4. to release

#150 v1.10.1
  appinfo/info.xml
Labels: 3. to review

#152 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#154 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
