Repository nextcloud/workflow_script, pull requests merged in 2023-11, with the labels that each got.

#212 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#213 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#211 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#210 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#216 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#214 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#217 test(psalm): fix missing template-implements hint
  lib/Listener/RegisterFlowOperationsListener.php
Labels: 3. to review, technical debt

#218 fix(operation): groupfolder path is user independent
  lib/Operation.php
Labels: 3. to review, backport-request, bug

#221 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#222 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#224 1.12.1
  appinfo/info.xml
Labels: 3. to review

#223 1.11.3
  appinfo/info.xml
Labels: 3. to review

#230 [stable28] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#229 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
