Repository nextcloud/workflow_script, pull requests merged in 2023-06, with the labels that each got.

#168 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#173 [stable26] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#172 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#175 fix: do not use removed View::getLocalFolder()
  lib/Operation.php
Labels: 3. to review, backport-request

#176 build: do not include psalm.xml in release archive
  .nextcloudignore
Labels: 3. to review, backport-request

#181 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#180 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
