Repository nextcloud/workflow_script, pull requests merged in 2024-09, with the labels that each got.

#330 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#331 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#333 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#332 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#336 [stable30] build: 1.15.0
  .github/workflows/appstore-build-publish.yml
  appinfo/info.xml
Labels: 3. to review

#340 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#339 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#337 Add SPDX header
  .github/contributing.md
  .github/dependabot.yml
  .github/issue_template.md.license
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/reuse.yml
  .gitignore
  .nextcloudignore
  .php-cs-fixer.dist.php
  AUTHORS.md
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/CC0-1.0.txt
  LICENSES/MIT.txt
  README.md
  REUSE.toml
  appinfo/info.xml
  js/admin.js
  krankerl.toml
  lib/AppInfo/Application.php
  lib/BackgroundJobs/Launcher.php
  lib/Exception/PlaceholderNotSubstituted.php
  lib/Listener/RegisterFlowOperationsListener.php
  lib/Operation.php
  screenshots/flow-ui.png.license
Labels: 3. to review, technical debt

#345 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#344 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#343 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#342 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
