Repository nextcloud/workflow_script, pull requests merged in 2024-03, with the labels that each got.

#266 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#264 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#263 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#268 fix(Operation): getLocalFile returns false meanwhile
  lib/BackgroundJobs/Launcher.php
  lib/Operation.php
Labels: 3. to review, backport-request, bug

#269 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
